import { Unit } from './guardStore'

export const RiderG1: Unit = {
  name: 'RiderG1',
  BASEHP: 300,
  BASESTR: 100,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 65,
  vsSiegePercent: 54,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G1'
}
export const RiderG2: Unit = {
  name: 'RiderG2',
  BASEHP: 540,
  BASESTR: 180,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 98,
  vsSiegePercent: 81,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G2'
}
export const RiderG3: Unit = {
  name: 'RiderG3',
  BASEHP: 960,
  BASESTR: 320,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 146,
  vsSiegePercent: 122,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G3'
}
export const RiderG4: Unit = {
  name: 'RiderG4',
  BASEHP: 1740,
  BASESTR: 580,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 219,
  vsSiegePercent: 182,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G4'
}
export const RiderG5: Unit = {
  name: 'RiderG5',
  BASEHP: 3150,
  BASESTR: 1050,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 329,
  vsSiegePercent: 273,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G5'
}

export const SwordmanG1: Unit = {
  name: 'SwordmanG1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 40,
  vsHumanPercent: 105,
  vsMountedPercent: 20,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'swordsman',
  category: 'melee',
  level: 'S1'
}

export const SpearmanG1: Unit = {
  name: 'SpearmanG1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 80,
  vsHumanPercent: 0,
  vsMountedPercent: 39,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G1'
}
export const SpearmanG2: Unit = {
  name: 'SpearmanG2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 120,
  vsHumanPercent: 0,
  vsMountedPercent: 59,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G2'
}
export const SpearmanG3: Unit = {
  name: 'SpearmanG3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 180,
  vsHumanPercent: 0,
  vsMountedPercent: 88,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G3'
}
export const SpearmanG4: Unit = {
  name: 'SpearmanG4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 270,
  vsHumanPercent: 0,
  vsMountedPercent: 132,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G4'
}
export const SpearmanG5: Unit = {
  name: 'SpearmanG5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 405,
  vsHumanPercent: 0,
  vsMountedPercent: 197,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G5'
}
export const ArcherG1: Unit = {
  name: 'Archer G1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 67,
  vsMeleePercent: 52,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G1'
}
export const ArcherG2: Unit = {
  name: 'Archer G2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 101,
  vsMeleePercent: 78,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G2'
}
export const ArcherG3: Unit = {
  name: 'Archer G3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 151,
  vsMeleePercent: 117,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G3'
}
export const ArcherG4: Unit = {
  name: 'Archer G4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 226,
  vsMeleePercent: 176,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G4'
}
export const ArcherG5: Unit = {
  name: 'Archer G5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 339,
  vsMeleePercent: 263,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G5'
}
export const CatapultG1: Unit = {
  name: 'Catapult G1',
  BASEHP: 1500,
  BASESTR: 250,
  LEADERSHIP: 10,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 65,
  troop: 'catapult',
  category: 'siege',
  level: 'E1'
}

// export const army = [
//   RiderG1,
//   RiderG2,
//   RiderG3,
//   RiderG4,
//   RiderG5,
//   SwordmanG1,
//   SpearmanG1,
//   ArcherG1,
//   CatapultG1
// ]
