import { EngineerUnit, GuardsmanUnit, MercUnit, MonsterUnit, SpecialistUnit } from './types'

export const RiderG1: GuardsmanUnit = {
  tipo: 'army',
  name: 'RiderG1',
  BASEHP: 300,
  BASESTR: 100,
  LEADERSHIP: 2,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 65,
  vsSiegePercent: 54,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'rider',
  category: 'mounted',
  // group: 'guardsman',
  race: 'human',
  group: 'guardsman',
  level: 'G1'
}
export const RiderG2: GuardsmanUnit = {
  tipo: 'army',
  name: 'RiderG2',
  BASEHP: 540,
  BASESTR: 180,
  LEADERSHIP: 2,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 98,
  vsSiegePercent: 81,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'rider',
  category: 'mounted',
  race: 'human',
  group: 'guardsman',
  level: 'G2'
}
export const RiderG3: GuardsmanUnit = {
  tipo: 'army',
  name: 'RiderG3',
  BASEHP: 960,
  BASESTR: 320,
  LEADERSHIP: 2,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 146,
  vsSiegePercent: 122,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'rider',
  category: 'mounted',
  race: 'human',
  group: 'guardsman',
  level: 'G3'
}
export const RiderG4: GuardsmanUnit = {
  tipo: 'army',
  name: 'RiderG4',
  BASEHP: 1740,
  BASESTR: 580,
  LEADERSHIP: 2,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 219,
  vsSiegePercent: 182,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'rider',
  category: 'mounted',
  race: 'human',
  group: 'guardsman',
  level: 'G4'
}
export const RiderG5: GuardsmanUnit = {
  tipo: 'army',
  name: 'RiderG5',
  BASEHP: 3150,
  BASESTR: 1050,
  LEADERSHIP: 2,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 329,
  vsSiegePercent: 273,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'rider',
  category: 'mounted',
  race: 'human',
  group: 'guardsman',
  level: 'G5'
}

//--------------------------------
export const SwordmanS1: SpecialistUnit = {
  tipo: 'army',
  name: 'SwordmanS1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 40,
  vsHumanPercent: 105,
  vsMountedPercent: 20,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'swordsman',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S1'
}
export const SwordmanS2: SpecialistUnit = {
  tipo: 'army',
  name: 'SwordmanS2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 60,
  vsHumanPercent: 105,
  vsMountedPercent: 29,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'swordsman',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S2'
}
export const SwordmanS3: SpecialistUnit = {
  tipo: 'army',
  name: 'SwordmanS3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 90,
  vsHumanPercent: 105,
  vsMountedPercent: 44,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'swordsman',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S3'
}
export const SwordmanS4: SpecialistUnit = {
  tipo: 'army',
  name: 'SwordmanS4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 135,
  vsHumanPercent: 105,
  vsMountedPercent: 66,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'swordsman',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S4'
}
export const SwordmanS5: SpecialistUnit = {
  tipo: 'army',
  name: 'SwordmanS5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 203,
  vsHumanPercent: 105,
  vsMountedPercent: 99,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'swordsman',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S5'
}
//----------------------------
export const SpyS1: SpecialistUnit = {
  tipo: 'army',
  name: 'SpyS1',
  BASEHP: 75,
  BASESTR: 25,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spy',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S1'
}
export const SpyS2: SpecialistUnit = {
  tipo: 'army',
  name: 'SpyS2',
  BASEHP: 135,
  BASESTR: 45,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spy',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S2'
}
export const SpyS3: SpecialistUnit = {
  tipo: 'army',
  name: 'SpyS3',
  BASEHP: 240,
  BASESTR: 80,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spy',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S3'
}
export const SpyS4: SpecialistUnit = {
  tipo: 'army',
  name: 'SpyS4',
  BASEHP: 450,
  BASESTR: 150,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spy',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S4'
}
export const SpyS5: SpecialistUnit = {
  tipo: 'army',
  name: 'SpyS5',
  BASEHP: 780,
  BASESTR: 260,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spy',
  category: 'melee',
  race: 'human',
  group: 'specialist',
  level: 'S5'
}

//----------------------------------
export const SpearmanG1: GuardsmanUnit = {
  tipo: 'army',
  name: 'SpearmanG1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 80,
  vsHumanPercent: 0,
  vsMountedPercent: 39,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spearman',
  category: 'melee', // vs beast||mounted
  race: 'human',
  group: 'guardsman',
  level: 'G1'
}
export const SpearmanG2: GuardsmanUnit = {
  tipo: 'army',
  name: 'SpearmanG2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 120,
  vsHumanPercent: 0,
  vsMountedPercent: 59,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spearman',
  category: 'melee',
  race: 'human',
  group: 'guardsman',
  level: 'G2'
}
export const SpearmanG3: GuardsmanUnit = {
  tipo: 'army',
  name: 'SpearmanG3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 180,
  vsHumanPercent: 0,
  vsMountedPercent: 88,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spearman',
  category: 'melee',
  race: 'human',
  group: 'guardsman',
  level: 'G3'
}
export const SpearmanG4: GuardsmanUnit = {
  tipo: 'army',
  name: 'SpearmanG4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 270,
  vsHumanPercent: 0,
  vsMountedPercent: 132,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spearman',
  category: 'melee',
  race: 'human',
  group: 'guardsman',
  level: 'G4'
}
export const SpearmanG5: GuardsmanUnit = {
  tipo: 'army',
  name: 'SpearmanG5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 405,
  vsHumanPercent: 0,
  vsMountedPercent: 197,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'spearman',
  category: 'melee',
  race: 'human',
  group: 'guardsman',
  level: 'G5'
}

//----------------------------------
export const ArcherG1: GuardsmanUnit = {
  tipo: 'army',
  name: 'Archer G1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 67,
  vsMeleePercent: 52,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'archer',
  category: 'ranged',
  race: 'human',
  group: 'guardsman',
  level: 'G1'
}
export const ArcherG2: GuardsmanUnit = {
  tipo: 'army',
  name: 'Archer G2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 101,
  vsMeleePercent: 78,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'archer',
  category: 'ranged',
  race: 'human',
  group: 'guardsman',
  level: 'G2'
}
export const ArcherG3: GuardsmanUnit = {
  tipo: 'army',
  name: 'Archer G3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 151,
  vsMeleePercent: 117,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'archer',
  category: 'ranged',
  race: 'human',
  group: 'guardsman',
  level: 'G3'
}
export const ArcherG4: GuardsmanUnit = {
  tipo: 'army',
  name: 'Archer G4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 226,
  vsMeleePercent: 176,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'archer',
  category: 'ranged',
  race: 'human',
  group: 'guardsman',
  level: 'G4'
}
export const ArcherG5: GuardsmanUnit = {
  tipo: 'army',
  name: 'Archer G5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 339,
  vsMeleePercent: 263,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'archer',
  category: 'ranged',
  race: 'human',
  group: 'guardsman',
  level: 'G5'
}

//----------------------------------
export const CatapultE1: EngineerUnit = {
  tipo: 'army',
  name: 'Catapult E1',
  BASEHP: 1500,
  BASESTR: 250,
  LEADERSHIP: 10,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 65,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'catapult',
  category: 'siege',
  race: 'human',
  group: 'engineer',
  level: 'E1'
}
export const CatapultE2: EngineerUnit = {
  tipo: 'army',
  name: 'Catapult E2',
  BASEHP: 2700,
  BASESTR: 450,
  LEADERSHIP: 10,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 98,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'catapult',
  category: 'siege',
  race: 'human',
  group: 'engineer',
  level: 'E2'
}
export const CatapultE3: EngineerUnit = {
  tipo: 'army',
  name: 'Catapult E3',
  BASEHP: 4860,
  BASESTR: 810,
  LEADERSHIP: 10,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 146,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'catapult',
  category: 'siege',
  race: 'human',
  group: 'engineer',
  level: 'E3'
}
export const CatapultE4: EngineerUnit = {
  tipo: 'army',
  name: 'Catapult E4',
  BASEHP: 8750,
  BASESTR: 1460,
  LEADERSHIP: 10,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 219,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'catapult',
  category: 'siege',
  race: 'human',
  group: 'engineer',
  level: 'E4'
}
export const CatapultE5: EngineerUnit = {
  tipo: 'army',
  name: 'Catapult E5',
  BASEHP: 15800,
  BASESTR: 2630,
  LEADERSHIP: 10,
  AUTHORITY: 0,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 329,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'catapult',
  category: 'siege',
  race: 'human',
  group: 'engineer',
  level: 'E5'
}

//------------------------
export const mercEpicMonsterHunter: MercUnit = {
  tipo: 'merc',
  name: 'mercEpicMonsterHunter',
  BASEHP: 6090,
  BASESTR: 2030,
  LEADERSHIP: 0,
  AUTHORITY: 1,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 329,
  vsSiegePercent: 273,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsEpicMonster: 609,
  vsGiantPercent: 0,
  troop: 'merc',
  category: 'epic',
  race: 'human',
  group: 'guardsman',
  level: 'VI'
}
export const mercChariot: MercUnit = {
  tipo: 'merc',
  name: 'mercChariot',
  BASEHP: 11400,
  BASESTR: 3800,
  LEADERSHIP: 0,
  AUTHORITY: 2,
  DOMINANCE: 0,
  INITIATIVE: 10,
  vsRangedPercent: 493,
  vsSiegePercent: 410,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsEpicMonster: 0,
  vsGiantPercent: 0,
  troop: 'rider',
  category: 'mounted',
  race: 'human',
  group: 'guardsman',
  level: 'VI'
}

//------------------------------------
export const waterElemental: MonsterUnit = {
  tipo: 'monster',
  name: 'waterElemental',
  BASEHP: 5700,
  BASESTR: 1900,
  LEADERSHIP: 0,
  AUTHORITY: 0,
  DOMINANCE: 3,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 144,
  vsMeleePercent: 113,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'monster',
  category: 'ranged',
  race: 'elemental',
  group: 'monster',
  level: 'M3'
}
export const battleBoar: MonsterUnit = {
  tipo: 'monster',
  name: 'battleBoar',
  BASEHP: 11700,
  BASESTR: 3900,
  LEADERSHIP: 0,
  AUTHORITY: 0,
  DOMINANCE: 6,
  INITIATIVE: 10,
  vsRangedPercent: 113,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 144,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  troop: 'monster',
  race: 'beast',
  group: 'monster',
  category: 'mounted',
  level: 'M3'
}
export const emeraldDragon: MonsterUnit = {
  tipo: 'monster',
  name: 'emeraldDragon',
  BASEHP: 13500,
  BASESTR: 4500,
  LEADERSHIP: 0,
  AUTHORITY: 0,
  DOMINANCE: 7,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 185,
  vsGiantPercent: 72,
  vsEpicMonster: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'monster',
  race: 'dragon',
  group: 'monster',
  category: 'flying',
  level: 'M3'
}
export const stoneGargole: MonsterUnit = {
  tipo: 'monster',
  name: 'stoneGargole',
  BASEHP: 15600,
  BASESTR: 5200,
  LEADERSHIP: 0,
  AUTHORITY: 0,
  DOMINANCE: 8,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 72,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsGiantPercent: 0,
  vsEpicMonster: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 185,
  vsFortificationsPercent: 0,
  troop: 'monster',
  race: 'giant',
  group: 'monster',
  category: 'flying',
  level: 'M3'
}
