import { MercUnit, Unit } from './guardStore'

export const RiderG1: Unit = {
  name: 'RiderG1',
  BASEHP: 300,
  BASESTR: 100,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 65,
  vsSiegePercent: 54,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G1'
}
export const RiderG2: Unit = {
  name: 'RiderG2',
  BASEHP: 540,
  BASESTR: 180,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 98,
  vsSiegePercent: 81,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G2'
}
export const RiderG3: Unit = {
  name: 'RiderG3',
  BASEHP: 960,
  BASESTR: 320,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 146,
  vsSiegePercent: 122,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G3'
}
export const RiderG4: Unit = {
  name: 'RiderG4',
  BASEHP: 1740,
  BASESTR: 580,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 219,
  vsSiegePercent: 182,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G4'
}
export const RiderG5: Unit = {
  name: 'RiderG5',
  BASEHP: 3150,
  BASESTR: 1050,
  LEADERSHIP: 2,
  INITIATIVE: 10,
  vsRangedPercent: 329,
  vsSiegePercent: 273,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'G5'
}

//--------------------------------
export const SwordmanS1: Unit = {
  name: 'SwordmanS1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 40,
  vsHumanPercent: 105,
  vsMountedPercent: 20,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'swordsman',
  category: 'melee',
  level: 'S1'
}
export const SwordmanS2: Unit = {
  name: 'SwordmanS2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 60,
  vsHumanPercent: 105,
  vsMountedPercent: 29,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'swordsman',
  category: 'melee',
  level: 'S2'
}
export const SwordmanS3: Unit = {
  name: 'SwordmanS3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 90,
  vsHumanPercent: 105,
  vsMountedPercent: 44,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'swordsman',
  category: 'melee',
  level: 'S3'
}
export const SwordmanS4: Unit = {
  name: 'SwordmanS4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 135,
  vsHumanPercent: 105,
  vsMountedPercent: 66,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'swordsman',
  category: 'melee',
  level: 'S4'
}
export const SwordmanS5: Unit = {
  name: 'SwordmanS5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 203,
  vsHumanPercent: 105,
  vsMountedPercent: 99,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'swordsman',
  category: 'melee',
  level: 'S5'
}
//----------------------------
export const SpyS1: Unit = {
  name: 'SpyS1',
  BASEHP: 75,
  BASESTR: 25,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spy',
  category: 'melee',
  level: 'S1'
}
export const SpyS2: Unit = {
  name: 'SpyS2',
  BASEHP: 135,
  BASESTR: 45,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spy',
  category: 'melee',
  level: 'S2'
}
export const SpyS3: Unit = {
  name: 'SpyS3',
  BASEHP: 240,
  BASESTR: 80,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spy',
  category: 'melee',
  level: 'S3'
}
export const SpyS4: Unit = {
  name: 'SpyS4',
  BASEHP: 450,
  BASESTR: 150,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spy',
  category: 'melee',
  level: 'S4'
}
export const SpyS5: Unit = {
  name: 'SpyS5',
  BASEHP: 780,
  BASESTR: 260,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spy',
  category: 'melee',
  level: 'S5'
}

//----------------------------------
export const SpearmanG1: Unit = {
  name: 'SpearmanG1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 80,
  vsHumanPercent: 0,
  vsMountedPercent: 39,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee', // vs beast||mounted
  level: 'G1'
}
export const SpearmanG2: Unit = {
  name: 'SpearmanG2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 120,
  vsHumanPercent: 0,
  vsMountedPercent: 59,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G2'
}
export const SpearmanG3: Unit = {
  name: 'SpearmanG3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 180,
  vsHumanPercent: 0,
  vsMountedPercent: 88,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G3'
}
export const SpearmanG4: Unit = {
  name: 'SpearmanG4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 270,
  vsHumanPercent: 0,
  vsMountedPercent: 132,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G4'
}
export const SpearmanG5: Unit = {
  name: 'SpearmanG5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 405,
  vsHumanPercent: 0,
  vsMountedPercent: 197,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  troop: 'spearman',
  category: 'melee',
  level: 'G5'
}

//----------------------------------
export const ArcherG1: Unit = {
  name: 'Archer G1',
  BASEHP: 150,
  BASESTR: 50,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 67,
  vsMeleePercent: 52,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G1'
}
export const ArcherG2: Unit = {
  name: 'Archer G2',
  BASEHP: 270,
  BASESTR: 90,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 101,
  vsMeleePercent: 78,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G2'
}
export const ArcherG3: Unit = {
  name: 'Archer G3',
  BASEHP: 480,
  BASESTR: 160,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 151,
  vsMeleePercent: 117,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G3'
}
export const ArcherG4: Unit = {
  name: 'Archer G4',
  BASEHP: 870,
  BASESTR: 290,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 226,
  vsMeleePercent: 176,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G4'
}
export const ArcherG5: Unit = {
  name: 'Archer G5',
  BASEHP: 1560,
  BASESTR: 520,
  LEADERSHIP: 1,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 339,
  vsMeleePercent: 263,
  vsFortificationsPercent: 0,
  troop: 'archer',
  category: 'ranged',
  level: 'G5'
}

//----------------------------------
export const CatapultE1: Unit = {
  name: 'Catapult E1',
  BASEHP: 1500,
  BASESTR: 250,
  LEADERSHIP: 10,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 65,
  troop: 'catapult',
  category: 'siege',
  level: 'E1'
}
export const CatapultE2: Unit = {
  name: 'Catapult E2',
  BASEHP: 2700,
  BASESTR: 450,
  LEADERSHIP: 10,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 98,
  troop: 'catapult',
  category: 'siege',
  level: 'E2'
}
export const CatapultE3: Unit = {
  name: 'Catapult E3',
  BASEHP: 4860,
  BASESTR: 810,
  LEADERSHIP: 10,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 146,
  troop: 'catapult',
  category: 'siege',
  level: 'E3'
}
export const CatapultE4: Unit = {
  name: 'Catapult E4',
  BASEHP: 8750,
  BASESTR: 1460,
  LEADERSHIP: 10,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 219,
  troop: 'catapult',
  category: 'siege',
  level: 'E4'
}
export const CatapultE5: Unit = {
  name: 'Catapult E5',
  BASEHP: 15800,
  BASESTR: 2630,
  LEADERSHIP: 10,
  INITIATIVE: 10,
  vsRangedPercent: 0,
  vsSiegePercent: 0,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  //str * 20 ?
  vsFortificationsPercent: 329,
  troop: 'catapult',
  category: 'siege',
  level: 'E5'
}

//------------------------
export const mercEpicMonsterHunter: MercUnit = {
  name: 'mercEpicMonsterHunter',
  BASEHP: 6090,
  BASESTR: 2030,
  AUTHORITY: 1,
  INITIATIVE: 10,
  vsRangedPercent: 329,
  vsSiegePercent: 273,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsEpicMonster: 609,
  troop: 'merc',
  category: 'merc',
  level: 'VI'
}
export const mercChariot: MercUnit = {
  name: 'mercChariot',
  BASEHP: 11400,
  BASESTR: 3800,
  AUTHORITY: 2,
  INITIATIVE: 10,
  vsRangedPercent: 493,
  vsSiegePercent: 410,
  vsBeastPercent: 0,
  vsHumanPercent: 0,
  vsMountedPercent: 0,
  vsFlyingPercent: 0,
  vsMeleePercent: 0,
  vsFortificationsPercent: 0,
  vsEpicMonster: 0,
  troop: 'rider',
  category: 'mounted',
  level: 'VI'
}
